joint_0:
  ID: 0
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 1000
joint_1:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 1000
joint_2:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 1000
  #Homing_Offset: -341
joint_3:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 1000
joint_4:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 1000
joint_5:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 1000
      
